### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by OmarGoubail** [mrdotb/live_react#1]
Sorry to open an issue for what should be a discussion, but the project doesn't have discussions yet. I love both live svelte and live vue, but I was planning to implement live react myself, that is until I found this repo. I would like to contribute, is there a roadmap or anything in particular I can work on.

Amazing work btw!

**Comment by mrdotb** [comment]
I created some issues you can choose from. :)
If you have other ideas, you can open an issue, and we will discuss it.
