### ISSUE TITLE
nodejs worker is making my shell corrupted after quitting

### ISSUE THREAD

**Issue by mrdotb** [mrdotb/live_react#10]
When two esbuild watcher are run for SSR in dev env.
After quitting `iex` the terminal output is corrupted.

![image](https://github.com/user-attachments/assets/ab4c6d20-f81f-45b5-8b54-c1f8c29f2c58)

**Comment by roeeyn** [comment]
I believe that if we manage to fix this, the same solution would work for LiveSvelte as well. Do you have any idea how to fix it? I'm happy to help with it, as this issue annoys me every time it happens, but I'm not very sure what the problem may be.

**Comment by mrdotb** [comment]
Quite annoying indeed.
My theory is that it's related to special character sequence from esbuild or phoenix that log at similar time and corrupt the output.
I don't have time currently but things you could try is disabling colors and tweak every config in Elixir / Esbuild to get pure text output. Then at this point if the problem is gone you turn things one by one until you find the culprit.

**Comment by mrdotb** [comment]
https://elixirforum.com/t/shell-corruption-after-exiting-iex-with-node-js-port/67380
