### ISSUE TITLE
Copied package.json still uses old react folder instead of react-components

### ISSUE THREAD

**Issue by jgcardelus** [mrdotb/live_react#22]
Hi,

During a deployment of a Phoenix application w/ live_react I got an error saying that NodeJS couldn't find the module `server.js`

In the package.json file copied during the setup the `build-server` script was copying the `server.js` and `package.json` to `react` instead of to `react-components`:

```json
"build-server": "tsc && vite build --ssr js/server.js --out-dir ../priv/react --minify esbuild && echo '{\"type\": \"module\" } ' > ../priv/react/package.json"
```

Changing to 

```json
"build-server": "tsc && vite build --ssr js/server.js --out-dir ../priv/react-components --minify esbuild && echo '{\"type\": \"module\" } ' > ../priv/react-components/package.json"
```

Solved the issue.

Looking at the docs I've seen that in the [Adjusting your own package.json](https://hexdocs.pm/live_react/1.0.0-rc.3/installation.html#adjusting-your-own-package-json) section, this change is already made.

I can submit a quick PR if anyone's interested.

**Comment by mrdotb** [comment]
:wave: Seems that I forgot to update this part.
PR is welcome !
